name = "mobile-repair-tracker"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd backend && npm run build"

[functions]
directory = "backend/dist"

[env.production.vars]
FAST2SMS_API_KEY = "your-fast2sms-api-key-here" 