name: Deploy to Qovery

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        cd backend && npm ci
        
    - name: Build backend
      run: cd backend && npm run build
      
    - name: Deploy to Qovery
      uses: Qovery/qovery-action@v0.1.0
      with:
        qovery-token: ${{ secrets.QOVERY_TOKEN }}
        application-name: mobile-repair-tracker-backend
        environment-name: production 